name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build, test and analyze
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'tech-test-payment-api.sln'

    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.11.0