name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build, test and analyze
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'tech-test-payment-api.sln'

    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.11.0
      
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Coverlet
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global coverlet.console
        dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner begin /k:"guilhermelemke_venda_api" /o:"guilhermelemke" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml"
        dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
        dotnet test $SOLUTION --configuration $BUILD_CONFIG /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml
        dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"